apiVersion: apps/v1
kind: Deployment
metadata:
  name: ra-tls-secret-prov-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ra-tls-secret-prov-server
  template:
    metadata:
      labels:
        app: ra-tls-secret-prov-server
    spec:
      containers:
      - name: ra-tls-secret-prov-server-container
        image: <dockerhubusername>/<aks-secret-prov-server-img>
        ports:
        - containerPort: 4433
        resources:
          limits:
            kubernetes.azure.com/sgx_epc_mem_in_MiB: 10

# TODO: Requesting an SGX machine is not needed, but Intel DCAP libraries have a bug of trying to
# open the SGX driver (see  https://github.com/intel/linux-sgx/issues/756)

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: <AKS-DNS-NAME>
  name: ra-tls-secret-prov-server
spec:
  type: LoadBalancer
  ports:
  - port: 4433
  selector:
    app: ra-tls-secret-prov-server
